# Generated by Django 5.0.6 on 2025-03-01 09:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_aboutinline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assortiment/', verbose_name='Изображение')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ассортимент',
                'verbose_name_plural': 'АСсортименты',
            },
        ),
    ]
