# Generated by Django 5.0.6 on 2025-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_assortment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assortment',
            options={'verbose_name': 'Ассортимент', 'verbose_name_plural': 'Ассортименты'},
        ),
        migrations.AlterField(
            model_name='assortment',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
    ]
