# Generated by Django 5.0.6 on 2025-03-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_recipecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Категория (рецепты)', 'verbose_name_plural': 'Категории (рецепты)'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_category', to='secondary.recipecategory'),
        ),
    ]
