# Generated by Django 5.0.6 on 2025-03-03 09:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_alter_recipecategory_options_recipe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_title', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация об доставке')),
                ('guarantee', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация об горантии')),
                ('props', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Информация об реквизитах')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантии',
            },
        ),
    ]
