# Generated by Django 5.0.6 on 2025-03-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_alter_assortment_options_alter_assortment_title'),
        ('secondary', '0005_alter_recipecategory_options_recipe_category'),
    ]

    operations = [
    ]
