# Generated by Django 5.0.6 on 2025-03-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_guarantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guarentee', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='delivery_image',
            field=models.ImageField(blank=True, null=True, upload_to='guarentee', verbose_name='Фотография (доставке)'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='guarantee_image',
            field=models.ImageField(blank=True, null=True, upload_to='guarentee', verbose_name='Фотография (горантии)'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='props_image',
            field=models.ImageField(blank=True, null=True, upload_to='guarentee', verbose_name='Фотография (реквизиты)'),
        ),
    ]
