# Generated by Django 5.0.6 on 2025-03-01 20:05

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_merge_20250301_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assortiment/', verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание товара')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('description_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание товара 2')),
            ],
            options={
                'verbose_name': 'Подробнее',
                'verbose_name_plural': 'Подробнее',
            },
        ),
        migrations.CreateModel(
            name='DetailsInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(verbose_name='Номер(порядка)')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details_inline', to='secondary.details', verbose_name='Зоголовок')),
            ],
            options={
                'verbose_name': 'Подробнее',
                'verbose_name_plural': 'Подробнее',
            },
        ),
    ]
