# Generated by Django 5.0.6 on 2025-03-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0007_details_detailsinline'),
        ('secondary', '0008_guarantee_description_delivery_and_more'),
    ]

    operations = [
    ]
