# Generated by Django 5.0.6 on 2025-03-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_assortment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnMyCookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Сам mycook категория',
                'verbose_name_plural': 'Сам mycook категория',
            },
        ),
        migrations.CreateModel(
            name='OwnMyCook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('advantage_1', models.CharField(max_length=255, verbose_name='преимущество 1')),
                ('advantage_2', models.CharField(max_length=255, verbose_name='преимущество 2')),
                ('advantage_3', models.CharField(max_length=255, verbose_name='преимущество 3')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_title', to='secondary.ownmycookcategory')),
            ],
            options={
                'verbose_name': 'Сам mycook',
            },
        ),
    ]
