# Generated by Django 5.0.6 on 2025-03-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_ownmycookcategory_ownmycook'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownmycook',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Фотграфия'),
            preserve_default=False,
        ),
    ]
