# Generated by Django 5.0.6 on 2025-03-07 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0011_ownmycook_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyTheyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=700, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Почему выбирают нас?',
                'verbose_name_plural': 'Почему выбирают нас?',
            },
        ),
        migrations.CreateModel(
            name='WhyTheyChooseUsInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=700, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='why/', verbose_name='Фотография')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_inline', to='secondary.whytheychooseus')),
            ],
            options={
                'verbose_name': 'Почему выбирают нас?',
                'verbose_name_plural': 'Почему выбирают нас?',
            },
        ),
    ]
