# Generated by Django 5.0.6 on 2025-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0014_tasting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='video',
            field=models.FileField(upload_to='', verbose_name='Видео отчет'),
        ),
    ]
