version: '3.8'

services:
  db_mycook:
    image: postgres:15
    env_file: ../.env
    volumes:
      - postgres_data_abc:/var/lib/postgresql/data

  web_mycook:
    build:
      context: ..
      dockerfile: Dockerfile.local
    command: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --reload
    volumes:
      - ../:/app
    env_file: 
      - ../.env
    depends_on:
      - db_mycook
    expose:
      - "8000"
    ports:
      - "8000:8000" 

  nginx_mycook:
    image: nginx:latest
    ports:
      - "5001:80"  # Пробрасываем только порт 80 наружу
    volumes:
      - ../nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ../static:/app/static
      # - ./staticfiles:/app/staticfiles
      - ../media:/app/media
    depends_on:
      - web_mycook

volumes:
  postgres_data_abc:
  