# Generated by Django 5.0.6 on 2025-04-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='URL telegram'),
        ),
    ]
