# Generated by Django 5.0.6 on 2025-03-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_faqs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AddField(
            model_name='faqs',
            name='main_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Главный заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqs',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FAQsInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=255, verbose_name='Ответ')),
                ('faqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs_inline', to='cms.faqs')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
    ]
