# Generated by Django 5.0.6 on 2025-03-07 10:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_faqs_options_faqs_main_title_faqs_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_image', verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('button_1', models.CharField(max_length=255, verbose_name='Название для кнопки')),
                ('button_1_url', models.CharField(max_length=255, verbose_name='URL для кнопки')),
                ('button_2', models.CharField(max_length=255, verbose_name='Название для кнопки')),
                ('button_2_url', models.CharField(max_length=255, verbose_name='URL для кнопки')),
            ],
            options={
                'verbose_name': 'Главный баннер',
                'verbose_name_plural': 'Главный баннер',
            },
        ),
    ]
