# Generated by Django 5.0.6 on 2025-03-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_productbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=600, null=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
