# Generated by Django 5.0.6 on 2025-03-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL для вотс (доставка)')),
            ],
            options={
                'verbose_name': 'Ссылка для кнопки доставка',
                'verbose_name_plural': 'Ссылка для кнопки доставка',
            },
        ),
    ]
