# Generated by Django 5.0.6 on 2025-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_urlwhatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlwhatsapp',
            name='map',
            field=models.URLField(default=1, verbose_name='URL для контакт (карта)'),
            preserve_default=False,
        ),
    ]
