# Generated by Django 5.0.6 on 2025-04-03 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_whychooseus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychooseus',
            name='reason_2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Причина 2'),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='reason_3',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Причина 3'),
        ),
    ]
