# Generated by Django 5.0.6 on 2025-04-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_whychooseus_reason_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlwhatsapp',
            old_name='url',
            new_name='urls',
        ),
    ]
