# Generated by Django 5.0.6 on 2025-04-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_rename_url_urlwhatsapp_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlwhatsapp',
            old_name='urls',
            new_name='url',
        ),
    ]
